goLive public API changes
AdobeDocs/cloudmanager-api-docs pull request #219
Opened 2022-06-28 08:07 UTC by DhariniSomani

Adding public documentation for Go Live feature

## Description

## Related Issue

[CMGR-28264](https://jira.corp.adobe.com/browse/CMGR-28264)

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-29 11:19 UTC, bohnertchris requested changes

2022-06-29 11:19 UTC, bohnertchris commented on swagger-specs/api.yaml
> +    description: Describes a feedback
"Describes the feedback" or "Describes feedback"

2022-06-29 11:19 UTC, bohnertchris commented on swagger-specs/api.yaml
> +      description: Date when Go Live is planned
"Go Live" is not a proper noun and should not be capitalized.

2022-06-29 11:19 UTC, bohnertchris commented on swagger-specs/api.yaml
> +      description: Date when the program completed Go Live
"Go Live" is not a proper noun and should not be capitalized.

2022-06-29 11:19 UTC, bohnertchris commented on swagger-specs/api.yaml
> +        $ref: '#/definitions/Go Live dates'
"Go Live" is not a proper noun and should not be capitalized.

2022-06-29 11:19 UTC, bohnertchris commented on src/data/permissions.json
> +        "path": "/api/program/{programId}/feedbacks"
Probably can't be changed since this is likely already part of the API, but feedback is a non-count noun and has no plural form.

2022-07-04 04:29 UTC, DhariniSomani commented on src/data/permissions.json
> +        "path": "/api/program/{programId}/feedbacks"
yes, its already a part

2022-07-13 13:05 UTC, bohnertchris approved these changes

2022-07-13 13:06 UTC, merged