[CMGR-50790] update tutorial to use OAuth instead of JWT
AdobeDocs/cloudmanager-api-docs pull request #279
Opened 2024-03-07 06:23 UTC by amisha1609

## Description

[CMGR-50790](https://jira.corp.adobe.com/browse/CMGR-50790)

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-03-11 03:44 UTC, kritikash18 requested changes

2024-03-11 03:44 UTC, kritikash18 commented on src/pages/tutorial/4-getting-an-access-token.md
> +  const response = await fetch('https://ims-na1.adobelogin.com/ims/token/v3', {
I wouldn't recommend doing it this way. Earlier also there were 2 API calls but they were abstract under @adobe/jwt-auth library. I believe there would be a similar adobe library for oauth, please use that

2024-03-12 06:03 UTC, amisha1609 commented on src/pages/tutorial/4-getting-an-access-token.md
> +  const response = await fetch('https://ims-na1.adobelogin.com/ims/token/v3', {
I cannot find any such library for oauth. can you please share if you know it?

2024-03-12 06:35 UTC, kritikash18 commented on src/pages/tutorial/4-getting-an-access-token.md
> +  const response = await fetch('https://ims-na1.adobelogin.com/ims/token/v3', {
[https://github.com/adobe/aio-lib-ims-oauth](https://github.com/adobe/aio-lib-ims-oauth)

2024-03-14 03:43 UTC, kritikash18 commented on src/pages/tutorial/4-getting-an-access-token.md
> +  return responseData.access_token;
please test this piece of code thoroughly

2024-03-14 03:43 UTC, kritikash18 approved these changes

2024-03-14 03:44 UTC, kritikash18 commented on src/pages/tutorial/4-getting-an-access-token.md
> +  return responseData.access_token;
also fix failing checks

2024-03-14 15:19 UTC, merged